### ISSUE TITLE
"My Events" Widget and Route Implementation

### ISSUE THREAD

**Issue by nicholasamigo** [nicholasamigo/BeHere#54] opened 2023-03-30 20:22 UTC
As a Front-End developer of BeHere, I want a widget on the home page that displays personal events and their information, outside of settings, in an organized manner.

**Acceptance criteria**
- [x] Implement a "My Events" widget that is only visible when logged in that, when clicked, will route to another page on the website.
Within the "My Events" page:
- [ ] Implement a "Hosting" section that displays event cards I am currently hosting.        
- [ ] Implement an "Attending" section that displays event cards I will be attending in the future.
- [ ] Implement a "Completed" section that displays event cards I have previously attended.
 - [ ] Implement a "Cancelled" section that displays event cards that were canceled.

**Comment by ajp4707** [comment] 2023-03-30 21:23
- [ ] throw all this within a new Angular Component so we can move it around
 look up ng generate. Make this in the `components` folder

**Comment by ajp4707** [comment] 2023-04-16 01:24
this is a duplicate of #78

**Closed by ajp4707** 2023-04-16 01:24 UTC
